# Generated by Django 2.0.2 on 2018-02-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
