# Generated by Django 2.0.2 on 2018-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180223_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(max_length=70),
        ),
    ]
