# Generated by Django 2.0.2 on 2018-02-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180223_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='TarjetaCredito',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='usuario-image'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
