# Generated by Django 2.0.2 on 2018-02-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180223_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='update_at',
            new_name='fechaDevolucion',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='create_at',
            new_name='fecha_Alquier',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TarjetaCredito',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
