# Generated by Django 2.0.2 on 2018-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180223_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='description',
            new_name='Sinópsis',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='director',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peliculas',
            name='pais',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
