# Generated by Django 2.0.2 on 2018-02-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20180223_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pelicula', models.IntegerField(null=True)),
                ('f_debuelta', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.usuario')),
            ],
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
